### ISSUE TITLE
Website Not listing any Mods

### ISSUE THREAD

**Issue by DHSsonde** [RE3CON/uvmod#3]
http://uvmod.ddns.net/

I am not seeing any mods listed. I have tried different browsers (Edge, Firefox, Chrome, Opera, Brave) both on mobile and desktop adblocker & no adblocker same result.
![RE3CON-UVMOD](https://github.com/RE3CON/uvmod/assets/2681548/6eb2ff94-8957-4312-9afe-2432fbb159e7)

**Comment by RE3CON** [comment]
Thanks, I forgot something in code. Now it works again
